<?
include("../includes/display.inc.php");
include("../config.inc.php");
$sys_name = BS_SYS_NAME;

global $max_dl_size, $contact_email;
$content = print_title("About $sys_name");
$content .= "<p>$sys_name is a search engine specifically designed to catalog shared files on local networks.  $sys_name \"spiders\" an assigned set of IP addresses, looking for computers that have SMB sharing enabled.  SMB is a standard protocol created by Microsoft for local file sharing.  The \"Network Neighborhood\" utilizes SMB.  When $sys_name finds a computer with SMB enabled, it adds that computer to a host list.  $sys_name then scans that computer for open file shares.  If a share is not password protected (or the password is blank), $sys_name recurses through that computer's directories and catalogues any files it finds.
<p>$sys_name does not store files.  It simply catalogues open (public) shares and maintains a listing of the files it has found.  Users can then use the $sys_name web interface to query the database and find relevent files.  $sys_name rescans each computer every " . BS_SCAN_HOURS . " hours, in addition to performing hourly \"uptime\" checks to establish a reliabilty average for each computer on the network.
<p>$sys_name is run by a system called BranScan which was created by Danny Silverman (zeno -at- agblog -dot- com).  $sys_name is released under the terms of the <a href=\"http://www.gnu.org/licenses/gpl.html\">GNU General Public License</a>.
<p>$sys_name can also act as a conduit to allow users of non-Windows computers to download files.  $sys_name \"streams\" files from their servers to a client computer.  To access this functionality, search in \"Mac/Linux\" mode (automatically selected if you're coming from a Mac or Linux box and haven't changed how your browser identifies itself) and click the \"Alt\" link next to a file.  Note that this feature is limited to a maximum file size of " . BS_MAX_DL . " MB.
<p>Complete server statistics including the number and size of files indexed is available on the <a href=\"stats.php\">stats page</a>.  While $sys_name does not store any files itself, we are concerned about both privacy and legality.  For that reason, we keep no records linking visitors to search queries.  We do keep aggregate data on what searches are performed and how many unique visitors have used this site.  We will not release any of this information (except such as is publically available on the stats page) without a court order.
<p>Additionally, we are concerned about theft of intellectual property and copyright infringement.  While $sys_name does not and cannot technically filter files by name or content, we are willing and able to remove any illegal files from our indexes.  We will do so upon request from an appropriate legal entity, and will do so within 48 hours of notice.  We encourage copyright owners to content the owners of file servers directly to avoid having said files appear in our database again in the next scan.
<p>There is no need nor reason to have more than one $sys_name service running on a network.  More than one service will in no way improve accuracy or performance and will simply serve to annoy network admins and slow down network traffic.  Additially, software such as ShareScan is even <b>more</b> network-intensive and, ultimately, less useful and efficient anyway.  We encourage you to avoid any such programs.
<p>Any questions, comments, and correspondance can be directed to the site operator, <a href=\"mailto:" . BS_CONTACT . "\">" . BS_CONTACT . "</a>.";
return_page("Other", $content);
?>
