#!/usr/bin/php -q
<?php
require("../config.inc.php");
global $link_id;
$hours = $argv['1'];

# Use the default hours unless specified at invocation

# Sometimes hosts just aren't up at the two times we try 'em, so we're going
# to attempt to stagger the times a big by adding a random +- 2.
$hours = ($hours == "") ? BS_SCAN_HOURS + rand(-2,2) : $hours;

if($result = mysql_query("SELECT id FROM hosts WHERE (lastscan + INTERVAL $hours HOUR) < NOW() AND isup=1 ORDER BY id", $link_id)) {
	$count = mysql_num_rows($result);
	print "Beginning scan of $count computers not scanned in the last $hours hours.\n";
	for($i = 1; $i <= $count; $i++) {
		$row = mysql_fetch_array($result);
		$comp = $row['id'];
		# This routine is not foolproof but it works pretty well
		$numprocs = trim(exec("ps -au `whoami` | grep crawl-comp | wc -l"));
		while($numprocs >= BS_MAX_PROC) {
			print "-";
			sleep(1);
			$numprocs = trim(exec("ps -au `whoami` | grep crawl-comp | wc -l"));
		}
		print "+";
		exec("./crawl-comp $comp > /dev/null &");
		# $filename = date("Y-m-d-h-i-s");
		# exec("./crawl-comp $comp > $filename &");
	}
} else {
	die("No computers within the designated timeframe.\n");
}
?>
