#!/usr/bin/php -q
<?php
require("../config.inc.php");
require("../includes/subnets.inc.php");
global $subnets;
global $link_id;
$name = $argv['1'];
if($name == "")
	die("Usage: subnet-scan <subnet-name>
Subnet name corresponds to a subnet listed in the subnets.inc.php file\n");
$stuff = $subnets[$name];

$subnet = $stuff['0'];
$start = $stuff['1'];
$end = $stuff['2'];
print "Starting subnet $subnet...\n";
for($i = $start; $i <= $end; $i++) {
	$ip = "$subnet.$i";
	print "Scanning $ip...\n";
	$result = "";
	exec("/usr/bin/nmblookup -R -A " . trim($ip), $result);
	print "{$result['1']}";
	if($result['1']) {
		ereg("(.*)<[0-9]{2}>[^G]+[MH]", $result[1], $regs);
		$hostname = "";
		if($hostname = trim($regs[1])) {
			print "\nAdding host $hostname ($ip)...\n";
			add_host($hostname, $ip);
		}
	}
}

function add_host($hostname, $ip) {
	global $link_id;
	print "Seeing it it already exists...\n";
	# Apparently XOR is only in MySQL 4.x
	# if($result = mysql_query("SELECT id FROM hosts WHERE ip='$ip' XOR name='$hostname'", $link_id)) {
	print "SELECT id FROM hosts WHERE (ip='$ip' AND name!='$hostname') OR (ip!='$ip' AND name='$hostname')\n";
	if(mysql_num_rows($result = mysql_query("SELECT id FROM hosts WHERE (ip='$ip' AND name!='$hostname') OR (ip!='$ip' AND name='$hostname')", $link_id))) {
		print "It sure does!\n";
		while($return = mysql_fetch_array($result)) {
			print "Deleting a host ({$return['id']})...\n";
			mysql_query("DELETE FROM hosts WHERE id={$return['id']}", $link_id);
			mysql_query("DELETE FROM files WHERE host_id={$return['id']}", $link_id);
		}
	}
	print "SELECT id FROM hosts WHERE ip='$ip' AND name='$hostname'\n";
	if(mysql_num_rows(mysql_query("SELECT id FROM hosts WHERE ip='$ip' AND name='$hostname'", $link_id))) {
		print "We already have this host catalogued, so skipping...\n";
		return;
	} else {
		print "Adding this host to the table...\n";
		mysql_query("INSERT INTO hosts (name, ip) VALUES ('$hostname', '$ip')", $link_id);
	}
}
?>
