#!/usr/bin/php -q
<?php
include("../config.inc.php");
global $link_id;

# File name, SQL
$stats = array(
	"hosts-total.txt" => "SELECT count(*) as num FROM hosts",
	"hosts-sharing.txt" => "SELECT count(id) as num FROM hosts WHERE files > 0 AND size > 0",
	"visitors-total.txt" => "SELECT sum(hits_total) as num FROM users",
	"visitors-unique.txt" => "SELECT count(*) as num FROM users",
	"search-total.txt" => "SELECT sum(hits) as num FROM search_terms",
	"search-unique.txt" => "SELECT count(*) as num FROM search_terms",
	"size-mb.txt" => "SELECT sum(size)/1024/1024 as num FROM hosts",
	"size.txt" => "SELECT sum(size)/1024/1024/1024 as num FROM hosts",
	"files.txt" => "SELECT count(*) as num FROM files"
);

foreach($stats as $filename => $sql) {
	$result = mysql_fetch_array(mysql_query($sql, $link_id));
	$number = number_format(round($result['num'], 0));
	$file = fopen("../stats/" . $filename, w);
	fwrite($file, $number);
	print "Updated $filename\n";
}
?>
